#!/usr/bin/env python3
"""
Cybertron Session Exporter
============================
Export session transcripts and audit logs to Markdown or JSON.

Usage:
    /export markdown          → Save session as .md file
    /export json              → Save session as .json file
    /export audit             → View recent audit entries
"""
import json
import time
from pathlib import Path
from typing import List, Dict, Any, Optional

EXPORT_DIR = Path.home() / ".cybertron" / "exports"


class SessionExporter:
    def __init__(self):
        EXPORT_DIR.mkdir(parents=True, exist_ok=True)

    def export_markdown(self, session_id: str, messages: List[Dict[str, Any]],
                        goal: str = "", tool_calls: int = 0) -> Path:
        """Export a session transcript as a Markdown report."""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        filename = f"session_{session_id}_{timestamp}.md"
        path = EXPORT_DIR / filename

        lines = [
            "# Cybertron Session Report",
            "",
            f"**Session ID:** `{session_id}`",
            f"**Goal:** {goal}",
            f"**Tool Calls:** {tool_calls}",
            f"**Exported:** {time.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "---",
            "",
            "## Transcript",
            "",
        ]

        for msg in messages:
            role = msg.get("role", "system")
            text = msg.get("text", "")
            meta = msg.get("meta", "")
            ts = msg.get("timestamp", time.strftime("%H:%M:%S"))

            if role == "user":
                lines.append(f"> **You** ({ts})\n> {text}\n")
            elif role == "agent":
                lines.append(f"**Cybertron** ({ts})\n\n{text}\n")
            elif role == "tool":
                lines.append(f"```\nTOOL: {meta}\n{text}\n```\n")
            elif role == "result":
                lines.append(f"```\nRESULT\n{text}\n```\n")
            elif role == "system":
                lines.append(f"*{text}*\n")

        lines.extend([
            "",
            "---",
            "",
            "*Generated by Cybertron Agent Console*",
        ])

        path.write_text("\n".join(lines), encoding="utf-8")
        return path

    def export_json(self, session_id: str, messages: List[Dict[str, Any]],
                    goal: str = "", tool_calls: int = 0) -> Path:
        """Export a session transcript as structured JSON."""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        filename = f"session_{session_id}_{timestamp}.json"
        path = EXPORT_DIR / filename

        data = {
            "session_id": session_id,
            "goal": goal,
            "tool_calls": tool_calls,
            "exported_at": time.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "messages": messages,
        }

        path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
        return path

    def list_exports(self) -> List[Dict[str, Any]]:
        """List all exported session files."""
        exports = []
        for path in sorted(EXPORT_DIR.glob("session_*"), key=lambda p: p.stat().st_mtime, reverse=True):
            exports.append({
                "filename": path.name,
                "size": path.stat().st_size,
                "modified": path.stat().st_mtime,
            })
        return exports

    def get_export_path(self) -> Path:
        return EXPORT_DIR


# ─── Singleton ───────────────────────────────────────────────────────────────
_exporter_instance: Optional[SessionExporter] = None

def get_exporter() -> SessionExporter:
    global _exporter_instance
    if _exporter_instance is None:
        _exporter_instance = SessionExporter()
    return _exporter_instance
